export const generalConstant = {
    SOMETHING_WENT_WRONG: "ada yang salah silahkan coba lagi nanti !",
    TYPE_NOT_FOUND: "tipe tidak ditemukan",
    CATEGORY_NOT_FOUND: "kategori tidak ditemukan",
    PRODUCT_NOT_FOUND: "produk tidak ditemukan",
    WITHDRAWAL_NOT_FOUND: "penarikan tidak ditemukan",
    ORDER_NOT_FOUND: "pesanan tidak ditemukan",
    USER_NOT_FOUND: "user tidak ditemukan",
    CURRICULUM_NOT_FOUND: "curriculum tidak ditemukan",
    MIDTRANS_ERROR: "midtrans error",
    BALANCE_NOT_ENOUGH: "saldo tidak cukup",
    PRODUCT_ALREADY_EXISTS: "produk sudah ada di keranjang",
    WITHDRAW_MESSAGE:"penarikan sudah dilakukan silahkan tunggu 1x24 jam untuk dana masuk ke rekening anda",
    WITHDRAW_STATUS_INVALID: "status penarikan tidak valid",
    VOUCHER_NOT_FOUND: "voucher tidak ditemukan",
    VOUCHER_EXPIRED: "voucher sudah kadaluarsa",
    VOUCHER_CODE_ALREADY_EXISTS: "voucher sudah digunakan",
    ECOURSE_SUB_MATERIAL_NOT_FOUND: "sub materi tidak ditemukan",
    RATING_ALREADY_EXISTS: "anda sudah memberikan rating untuk produk ini",
}